steps:
  - name: python:3.10-slim
    id: "install requirements"
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    dir: "anomaly_detection/configs"
  - name: python:3.10-slim
    id: "unit tests"
    entrypoint: python
    args: ["-m", "pytest"]
    dir: "anomaly_detection/src/tests"
  - name: "gcr.io/cloud-builders/docker"
    id: "build container image"
    args:
      [
        "build",
        "-f",
        "serving.dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/anomaly-detection:$SHORT_SHA",
        "--network=cloudbuild",
        ".",
      ]
    dir: "anomaly_detection"
  - name: "gcr.io/cloud-builders/docker"
    id: "push container image to container registry"
    args: ["push", "gcr.io/$PROJECT_ID/anomaly-detection:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    id: "retagging"
    args:
      [
        "tag",
        "gcr.io/$PROJECT_ID/anomaly-detection:$SHORT_SHA",
        "gcr.io/$PROJECT_ID/anomaly-detection:latest",
      ]
options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
images:
  - gcr.io/$PROJECT_ID/anomaly-detection
timeout: 3600s
