steps:
  - name: python:3.10-slim
    id: "install requirements"
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    dir: "anomaly_detection/configs"
  - name: python:3.10-slim
    id: "unit tests"
    entrypoint: python
    args: ["-m", "pytest"]
    dir: "anomaly_detection/tests"
  - name: "gcr.io/cloud-builders/docker"
    id: "build container image"
    args: ["build", "-t", "gcr.io/test-rig-349313/anomaly-detection", "."]
    dir: "anomaly_detection"
  - name: "gcr.io/cloud-builders/docker"
    id: "push container image to container registry"
    args: ["push", "gcr.io/test-rig-349313/anomaly-detection"]
options:
  machineType: 'E2_HIGHCPU_8'
images:
  - gcr.io/test-rig-349313/anomaly-detection
timeout: 3600s
