steps:
  - name: python
    id: "install requirements"
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  - name: python
    id: "unit tests"
    entrypoint: python
    args: ["-m", "pytest"]
  - name: "gcr.io/cloud-builders/docker"
    id: "build container image"
    args: ["build", "-f","serving.dockerfile","-t", "gcr.io/test-rig-349313/forecasting", "."]
    dir: "forecasting"
  - name: "gcr.io/cloud-builders/docker"
    id: "push container image to container registry"
    args: ["push", "gcr.io/test-rig-349313/forecasting"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy container image to cloud run"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "forecasting",
        "--image",
        "gcr.io/test-rig-349313/forecasting",
        "--region",
        "europe-west1",
        "--cpu",
        "4",
        "--memory",
        "8Gi",
        "--timeout",
        "3600",
        "--allow-unauthenticated",
        "--platform",
        "managed",
        "--port", 
        "8081"
      ]
options:
  machineType: 'E2_HIGHCPU_8'
images:
  - gcr.io/test-rig-349313/forecasting
timeout: 3600s
