steps:
  - name: python:3.10-slim
    id: "install requirements"
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    dir: "forecasting/configs"
  - name: python:3.10-slim
    id: "unit tests"
    entrypoint: python
    args: ["-m", "pytest"]
    dir: "forecasting/tests"
  - name: "gcr.io/cloud-builders/docker"
    id: "build container image"
    args: ["build", "-f","serving.dockerfile","-t", "gcr.io/test-rig-349313/forecasting", "."]
    dir: "forecasting"
  - name: "gcr.io/cloud-builders/docker"
    id: "push container image to container registry"
    args: ["push", "gcr.io/test-rig-349313/forecasting"]
options:
  machineType: 'E2_HIGHCPU_8'
images:
  - gcr.io/test-rig-349313/forecasting
timeout: 3600s
